Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in
sklearn.datasets.

In [40]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [6]:
x,y = load_iris(return_X_y=TKNeighborsClassifierrue)

In [8]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=45)

In [10]:
classifier = KNeighborsClassifier()
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)

print(f"Accuracy: {accuracy_score(y_test, y_pred)}")

Accuracy: 0.9473684210526315


Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in
sklearn.datasets.

In [12]:
import pandas as pd
import numpy as np
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]
raw_df.head()

0      1      2    3      4      5     6       7    8      9     10
0    0.00632  18.00   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3
1  396.90000   4.98  24.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   NaN
2    0.02731   0.00   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8
3  396.90000   9.14  21.60  NaN    NaN    NaN   NaN     NaN  NaN    NaN   NaN
4    0.02729   0.00   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8

In [21]:
raw_df.values

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.0000e+00, 2.9600e+02,
        1.5300e+01],
       [3.9690e+02, 4.9800e+00, 2.4000e+01, ...,        nan,        nan,
               nan],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 2.0000e+00, 2.4200e+02,
        1.7800e+01],
       ...,
       [3.9345e+02, 6.4800e+00, 2.2000e+01, ...,        nan,        nan,
               nan],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 1.0000e+00, 2.7300e+02,
        2.1000e+01],
       [3.9690e+02, 7.8800e+00, 1.1900e+01, ...,        nan,        nan,
               nan]])

In [23]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score

In [25]:
regressor = KNeighborsRegressor()
regressor.fit(X_train,y_train)
y_pred = regressor.predict(X_test)

print(f"R2 Score: {r2_score(y_test, y_pred)}")

R2 Score: 0.9641053587647593


Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using
cross-validation on load_iris dataset in sklearn.datasets.

In [28]:
a,b = load_iris(return_X_y=True)

In [32]:
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [34]:
kn = KNeighborsClassifier()

In [80]:
x_train,x_test,y_train,y_test = train_test_split(a,b,test_size=0.25,random_state=45)

In [106]:
k_values = list(range(1,25))

In [108]:
c_score = []

In [112]:
for k in k_values:
    kn = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(kn,a,b,cv=5,scoring = 'accuracy')
    c_score.append(scores.mean())

In [116]:
opt_k = k_values[c_score.index(max(c_score))]

IndexError: list index out of range

In [90]:
print(f"The optimal K value is {opt_k} with a cross-validation accuracy of {max(c_score)}")
optimal_knn_classifier = KNeighborsClassifier(n_neighbors=opt_k)
optimal_knn_classifier.fit(x_train, y_train)
y_pred = optimal_knn_classifier.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")

The optimal K value is 1 with a cross-validation accuracy of 0.9733333333333334
Accuracy: 0.9473684210526315


Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in
sklearn.datasets.

In [123]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

X_train,X_test,y_train,y_test = train_test_split(data,target,test_size=0.25,random_state=45)

In [124]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

regressor = KNeighborsRegressor()
regressor.fit(X_train,y_train)
y_pred = regressor.predict(X_test)

print(f"R2 Score: {r2_score(y_test, y_pred)}")

R2 Score: 0.758193487336346


Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on
load_iris dataset in sklearn.datasets.

In [128]:
from sklearn.datasets import load_iris

In [130]:
ir = load_iris()

In [134]:
x,y = load_iris(return_X_y = True)

In [138]:
from sklearn.model_selection import train_test_split

In [140]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size=0.3)

In [142]:
x_train.shape

(105, 4)

In [144]:
cl = KNeighborsClassifier(weights='distance')

In [148]:
cl.fit(x_train,y_train)

KNeighborsClassifier(weights='distance')

In [150]:
y_pred = cl.predict(x_test)

In [154]:
accuracy = cl.score(x_test, y_test)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 1.00


Q6. Implement a function to standardise the features before applying KNN classifier.

In [163]:
from sklearn.preprocessing import StandardScaler

def std_features(X_train, X_test):
    sc = StandardScaler()
    x_trains= sc.fit_transform(X_train)
    x_tests = sc.transform(X_test)
    return x_trains, x_tests

x_trains,x_tests = std_features(x_train,x_test)

In [165]:
print(x_train,x_tests)

[[5.5 2.4 3.7 1. ]
 [6.3 2.8 5.1 1.5]
 [6.4 3.1 5.5 1.8]
 [6.6 3.  4.4 1.4]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [7.6 3.  6.6 2.1]
 [5.6 3.  4.5 1.5]
 [5.1 3.5 1.4 0.2]
 [7.7 2.8 6.7 2. ]
 [5.8 2.7 4.1 1. ]
 [5.2 3.4 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.1 3.8 1.9 0.4]
 [5.  2.  3.5 1. ]
 [6.3 2.7 4.9 1.8]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.1 3.3 1.7 0.5]
 [5.6 2.7 4.2 1.3]
 [5.1 3.4 1.5 0.2]
 [5.7 3.  4.2 1.2]
 [7.7 3.8 6.7 2.2]
 [4.6 3.2 1.4 0.2]
 [6.2 2.9 4.3 1.3]
 [5.7 2.5 5.  2. ]
 [5.5 4.2 1.4 0.2]
 [6.  3.  4.8 1.8]
 [5.8 2.7 5.1 1.9]
 [6.  2.2 4.  1. ]
 [5.4 3.  4.5 1.5]
 [6.2 3.4 5.4 2.3]
 [5.5 2.3 4.  1.3]
 [5.4 3.9 1.7 0.4]
 [5.  2.3 3.3 1. ]
 [6.4 2.7 5.3 1.9]
 [5.  3.3 1.4 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 2.4 3.8 1.1]
 [6.7 3.  5.  1.7]
 [4.9 3.1 1.5 0.2]
 [5.8 2.8 5.1 2.4]
 [5.  3.4 1.5 0.2]
 [5.  3.5 1.6 0.6]
 [5.9 3.2 4.8 1.8]
 [5.1 2.5 3.  1.1]
 [6.9 3.2 5.7 2.3]
 [6.  2.7 5.1 1.6]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [5.5 2.5 4.  1.3]
 [4.4 2.9 1.4 0.2]
 [4.3 3.  1.

Q7. Write a Python function to calculate the euclidean distance between two points.

In [168]:
def euclidean_distance(x,y):
    x1,x2=x
    y1,y2=y
    dist = np.sqrt((x2-x1)**2 +(y2-y1)**2)
    return dist

In [170]:
point1 = (1, 2)
point2 = (4, 6)
distance = euclidean_distance(point1, point2)
print(f"Euclidean Distance: {distance:.2f}")

Euclidean Distance: 2.24


In [172]:
Q8. Write a Python function to calculate the manhattan distance between two points.

SyntaxError: invalid syntax (2858436392.py, line 1)